CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin:
	dc.w	CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_000E-CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin
	dc.w	CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_0020-CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin
	dc.w	CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_003A-CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin
	dc.w	CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_0054-CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin
	dc.w	CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_005E-CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin
	dc.w	CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_0068-CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin
	dc.w	CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_0072-CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin

CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_000E:	dc.b 2
	dc.b $F8, 9, 0, 0, $E8
	dc.b $F8, 9, 0, 6, 0

CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_0020:	dc.b 3
	dc.b $F8, 9, 0, 0, $E8
	dc.b $F8, 5, 0, $C, 0
	dc.b 8, 5, 0, $10, 2

CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_003A:	dc.b 3
	dc.b $F8, 9, 0, 0, $E8
	dc.b $F8, 5, 0, $C, 0
	dc.b 8, 5, 0, $14, 2

CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_0054:	dc.b 1
	dc.b $F0, 1, 0, $14, 4

CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_005E:	dc.b 1
	dc.b $F0, 1, 0, $16, 4

CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_0068:	dc.b 1
	dc.b $10, 1, 0, $18, 9

CUsersSysmarkIP1DownloadsSonicHackingStuffSonic2NickArcadeDisassemblymainmappingsspriteobj4Bbin_0072:	dc.b 1
	dc.b $10, 1, 0, $1A, 9

	even
